---
name: Base workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  included1:
    needs: job1
    uses: ./.github/workflows/include.yaml
    with:
      name: Afonso
    secrets:
      age: ${{ secrets.RA_AGE }}
  result:
    runs-on: ubuntu-latest
    needs: included1
    steps:
      - name: Show results
        run: |
          echo "The result is: ${{ needs.included1.outputs.result }}"
...
