---
name: Conditionals

on:
  workflow_dispatch:

env:
  FILE: "file.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        id: build
        run: |
          echo 'Content of file with error.' > ${{ env.FILE }}
          exit 1

      - name: Upload the build file
        if: ${{ failure() && steps.build.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: ${{ env.FILE }}

  report:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download report results
        uses: actions/download-artifact@v3
        with:
          name: file

      - name: Show report results
        run: cat ${{ env.FILE }}
...
